// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": boolean
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.required": { message?: string }
    "meta.default": string
    "meta.example": string
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "expect.array.uniqueItems": { message?: string }
    "expect.array.key": { message?: string }
    "emit.jsonSchema": boolean
    "db.patch.strategy": string
    "db.table": string | true
    "db.table.filterable": string | true
    "db.table.sortable": string | true
    "db.table.renamed": string
    "db.table.preferredId.uniqueIndex": string | true
    "db.schema": string
    "db.index.plain": ({ name?: string, sort?: string })[]
    "db.index.unique": (string | true)[]
    "db.index.fulltext": ({ name?: string, weight?: number })[]
    "db.column": string
    "db.column.renamed": string
    "db.column.collate": string
    "db.column.precision": { precision: number, scale: number }
    "db.column.dimension": boolean
    "db.column.measure": boolean
    "db.column.filterable": boolean
    "db.column.sortable": boolean
    "db.default": string
    "db.default.increment": number | true
    "db.default.uuid": boolean
    "db.default.now": boolean
    "db.json": boolean
    "db.ignore": boolean
    "db.http.path": string
    "db.sync.method": string
    "db.depth.limit": number
    "db.rel.FK": string | true
    "db.rel.to": string | true
    "db.rel.from": string | true
    "db.rel.onDelete": string
    "db.rel.onUpdate": string
    "db.rel.via": import("@atscript/typescript/utils").AtscriptRef
    "db.rel.filter": import("@atscript/typescript/utils").AtscriptQueryNode
    "db.view": string | true
    "db.view.for": import("@atscript/typescript/utils").AtscriptRef
    "db.view.joins": ({ target: import("@atscript/typescript/utils").AtscriptRef, condition: import("@atscript/typescript/utils").AtscriptQueryNode })[]
    "db.view.filter": import("@atscript/typescript/utils").AtscriptQueryNode
    "db.view.materialized": boolean
    "db.view.renamed": string
    "db.view.having": import("@atscript/typescript/utils").AtscriptQueryNode
    "db.agg.sum": string
    "db.agg.avg": string
    "db.agg.count": string | true
    "db.agg.min": string
    "db.agg.max": string
    "db.search.vector": { dimensions: number, similarity?: string, indexName?: string }
    "db.search.vector.threshold": number
    "db.search.filter": (string)[]
    "db.amount.currency": string
    "db.amount.currency.ref": string
    "db.unit": string
    "db.unit.ref": string
    "ui.type": string
    "ui.form.placeholder": string
    "ui.form.hint": string
    "ui.form.classes": (string)[]
    "ui.form.styles": (string)[]
    "ui.form.autocomplete": string
    "ui.form.disabled": boolean
    "ui.form.options": ({ label: string, value?: string })[]
    "ui.form.order": number
    "ui.form.type": string
    "ui.form.component": string
    "ui.form.hidden": boolean
    "ui.form.attr": ({ name: string, value: string })[]
    "ui.form.width": string
    "ui.form.icon": string
    "ui.form.submit.text": string
    "ui.form.action": { id: string, label?: string }
    "ui.form.validate": (string)[]
    "ui.form.fn.title": string
    "ui.form.fn.submit.text": string
    "ui.form.fn.submit.disabled": string
    "ui.form.fn.label": string
    "ui.form.fn.description": string
    "ui.form.fn.hint": string
    "ui.form.fn.placeholder": string
    "ui.form.fn.disabled": string
    "ui.form.fn.hidden": string
    "ui.form.fn.readonly": string
    "ui.form.fn.value": string
    "ui.form.fn.classes": string
    "ui.form.fn.styles": string
    "ui.form.fn.options": string
    "ui.form.fn.attr": ({ name: string, fn: string })[]
    "ui.table.width": string
    "ui.table.component": string
    "ui.table.hidden": boolean
    "ui.table.attr": ({ name: string, value: string })[]
    "ui.table.classes": (string)[]
    "ui.table.styles": (string)[]
    "ui.table.type": string
    "ui.table.order": number
    "ui.table.fn.attr": ({ name: string, fn: string })[]
    "ui.table.fn.classes": string
    "ui.table.fn.styles": string
    "ui.dict.label": boolean
    "ui.dict.descr": boolean
    "ui.dict.attr": (boolean)[]
    "ui.dict.filterable": boolean
    "ui.dict.sortable": boolean
    "ui.dict.searchable": boolean
    "ui.array.add.label": string
    "ui.array.remove.label": string
    "wf.context.pass": (string)[]
    "wf.context.copy": string
    "wf.action.withData": string
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "url" | "ipv4" | "ipv6" | "ip" | "char" | "required" | "number" | "positive" | "negative" | "single" | "double" | "int" | "int8" | "int16" | "int32" | "int64" | "uint8" | "byte" | "uint16" | "port" | "uint32" | "uint64" | "timestamp" | "created" | "updated" | "decimal" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom" | "db" | "vector" | "currencyCode" | "ui" | "action" | "paragraph" | "select" | "radio" | "checkbox"
}
// prettier-ignore-end