packages:
  - packages/*

catalogMode: prefer

catalog:
  "@atscript/core": ^0.1.41
  "@atscript/typescript": ^0.1.41
  "@prostojs/deserialize-fn": ^0.0.5
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  vue: ^3

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
