packages:
  - packages/*
  - docs

catalog:
  "@atscript/core": ^0.1.41
  "@atscript/typescript": ^0.1.41
  "@prostojs/deserialize-fn": ^0.0.5
  "@tanstack/vue-virtual": ^3.13.23
  "@tsdown/css": ^0.21.4
  "@types/node": ^24
  "@uniqu/core": ^0.1.2
  "@vitejs/plugin-vue": ^6
  "@vue/test-utils": ^2
  happy-dom: ^18
  typescript: ^5
  unplugin-atscript: ^0.1.41
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3
  vue-router: ^4
  vue-tsc: ^3.2.6

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
