packages:
  - packages/*
  - docs

catalog:
  "@atscript/core": ^0.1.48
  "@atscript/db": ^0.1.52
  "@atscript/db-client": ^0.1.52
  "@atscript/db-sql-tools": ^0.1.52
  "@atscript/db-sqlite": ^0.1.52
  "@atscript/moost-db": ^0.1.52
  "@atscript/typescript": ^0.1.48
  "@moostjs/event-http": ^0.6.7
  "@moostjs/event-wf": ^0.6.7
  "@moostjs/vite": ^0.6.7
  "@playwright/test": ^1.58.2
  "@prostojs/deserialize-fn": ^0.0.5
  "@swc/core": ^1.15.18
  "@tanstack/vue-virtual": ^3.13.23
  "@tsdown/css": ^0.21.4
  "@types/node": ^24
  "@uniqu/core": ^0.1.5
  "@vitejs/plugin-vue": ^6
  "@vue/test-utils": ^2
  "@vueuse/core": ^14.2.1
  "@wooksjs/event-core": ^0.7.9
  "@wooksjs/event-wf": ^0.7.9
  happy-dom: ^18
  "moost": ^0.6.7
  reka-ui: ^2.9.2
  typescript: ^5
  unplugin-atscript: ^0.1.48
  unplugin-swc: ^1.5.9
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3
  vue-router: ^4
  vue-tsc: ^3.2.6

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
