/**
 * Minimal global declarations for AtscriptMetadata and AtscriptPrimitiveTags.
 *
 * These are normally generated by the `asc` CLI from `.as` files.
 * Since this is a library without `.as` files, we declare the empty
 * base interfaces. Consumer projects augment these via their generated
 * `atscript.d.ts`.
 */

// eslint-disable-next-line @typescript-eslint/no-empty-object-type -- augmented by generated atscript.d.ts
declare interface AtscriptMetadata {}
declare type AtscriptPrimitiveTags = string;
