// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": boolean
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.required": { message?: string }
    "meta.default": string
    "meta.example": string
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "expect.array.uniqueItems": { message?: string }
    "expect.array.key": { message?: string }
    "emit.jsonSchema": boolean
    "ui.type": string
    "ui.form.placeholder": string
    "ui.form.hint": string
    "ui.form.classes": (string)[]
    "ui.form.styles": (string)[]
    "ui.form.autocomplete": string
    "ui.form.disabled": boolean
    "ui.form.options": ({ label: string, value?: string })[]
    "ui.form.order": number
    "ui.form.type": string
    "ui.form.component": string
    "ui.form.hidden": boolean
    "ui.form.attr": ({ name: string, value: string })[]
    "ui.form.grid.colSpan": { desktop: string, narrow?: string }
    "ui.form.grid.rowSpan": { desktop: string, narrow?: string }
    "ui.form.icon": string
    "ui.form.submit.text": string
    "ui.form.action": { id: string, label?: string }
    "ui.table.width": string
    "ui.table.component": string
    "ui.table.hidden": boolean
    "ui.table.attr": ({ name: string, value: string })[]
    "ui.table.classes": (string)[]
    "ui.table.styles": (string)[]
    "ui.table.type": string
    "ui.table.order": number
    "ui.dict.label": boolean
    "ui.dict.descr": boolean
    "ui.dict.attr": (boolean)[]
    "ui.dict.filterable": boolean
    "ui.dict.sortable": boolean
    "ui.dict.searchable": boolean
    "ui.array.add.label": string
    "ui.array.remove.label": string
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "url" | "ipv4" | "ipv6" | "ip" | "char" | "required" | "number" | "positive" | "negative" | "single" | "double" | "int" | "int8" | "int16" | "int32" | "int64" | "uint8" | "byte" | "uint16" | "port" | "uint32" | "uint64" | "timestamp" | "created" | "updated" | "decimal" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom" | "ui" | "action" | "paragraph" | "select" | "radio" | "checkbox"
}
// prettier-ignore-end