/* oxlint-disable */
/* eslint-disable */
/**
 * 🪄 This file was generated by Atscript (@atscript/db model manifest)
 * Do not edit this file!
 *
 * Re-generate with `npx asc -f dts`.
 */
import { AuditLogTable } from "./schemas/audit-log.as";
import { CategoriesTable } from "./schemas/categories.as";
import { CustomersTable } from "./schemas/customers.as";
import { OrdersTable } from "./schemas/orders.as";
import { ProductsTable } from "./schemas/products.as";
import { RolesTable } from "./schemas/roles.as";
import { TaskBoardView } from "./schemas/task-board.as";
import { TasksTable } from "./schemas/tasks.as";
import { UsersTable } from "./schemas/users.as";
import { WfStateRow } from "./schemas/wf-state.as";

export const dbTables = [
  AuditLogTable,
  CategoriesTable,
  CustomersTable,
  OrdersTable,
  ProductsTable,
  RolesTable,
  TasksTable,
  UsersTable,
  WfStateRow,
] as const;
export const dbViews = [TaskBoardView] as const;
/** Every @db.table / @db.view model in this project. */
export const atscriptModels = [...dbTables, ...dbViews] as const;
/** Models grouped by @db.space (absent annotation → "default"). */
export const modelsBySpace = {
  default: atscriptModels,
} as const;
